[project]
name = "21-days-21-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fg-data-profiling>=4.20.0",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "nltk>=3.10.3",
    "notebook>=7.6.2",
    "pandas>=2.2,<3",
    "rich>=15.0.0",
    "seaborn>=0.13.2",
    "setuptools>=84.0.0",
]
